services:

  customer-db:
    image: postgres:17
    container_name: customer-postgres
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_password
    ports:
      - "5433:5432"
    volumes:
      - customer_postgres_data:/var/lib/postgresql/data

  account-db:
      image: postgres:17
      container_name: account-postgres
      environment:
        POSTGRES_DB: account_db
        POSTGRES_USER: account_user
        POSTGRES_PASSWORD: account_password
      ports:
        - "5434:5432"
      volumes:
        - account_postgres_data:/var/lib/postgresql/data

volumes:
  customer_postgres_data:
  account_postgres_data: